version: 2.1
jobs:
  build:
    working_directory: ~/incubator-superset
    docker:
      - image: docker:18.09.6-git

    steps:
      - checkout
      - setup_remote_docker:
         version: 18.09.3
         docker_layer_caching: true

      - run:
         name: list files
         command: ls -lsrt ~/incubator-superset

      - run:
         name: Build Docker image
         command: docker build -t $DOCKER_IMAGE_NAME -f ~/incubator-superset/contrib/docker/Dockerfile .

      - run:
          name: Push to DockerHub
          command: |
            docker login $DOCKER_REGISTRY -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
            docker push $DOCKER_IMAGE_NAME

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - dev
                - circleci
