version: 2.1
jobs:
  build:
    working_directory: ~/incubator-superset
    docker:
      - image: docker:18.09.6-git

    steps:
      - checkout
      - setup_remote_docker:
         version: 18.09.3
         docker_layer_caching: true

      - run:
         name: list files
         command: ls -lsrt ~/incubator-superset

      - run:
         name: Build Docker image
         command: docker build -t $DOCKER_REGISTRY/$PROJECT_ID/$DOCKER_IMAGE_NAME:$CIRCLE_BUILD_NUM -f ~/incubator-superset/contrib/docker/Dockerfile .

      - run:
          name: Push to Docker registry container
          command: |
            docker login -u $DOCKER_REGISTRY_USERNAME -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY
            docker push $DOCKER_REGISTRY/$PROJECT_ID/$DOCKER_IMAGE_NAME:$CIRCLE_BUILD_NUM
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - dev
                - circleci
